In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# load data 
patient_data = pd.read_csv('../AI/Breast Cancer Data.csv')

In [4]:
patient_data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [30]:
# split data into feature matrix (X) and target vector (y)
X = patient_data.iloc[:, 1:-1].values
y = patient_data.iloc[:, -1].values

In [31]:
# Split into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [32]:
# apply scaler
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train  = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [33]:
# logistic regression
from sklearn.linear_model import LogisticRegression
lRegClassifier = LogisticRegression()
lRegClassifier.fit(X_train, y_train)

LogisticRegression()

In [34]:
# k- nearest neighbour
from sklearn.neighbors import KNeighborsClassifier
knnClassifier = KNeighborsClassifier()
knnClassifier.fit(X_train, y_train)

KNeighborsClassifier()

In [35]:
# Suppport vector machine classifier
from sklearn.svm import SVC
svClassifier = SVC(kernel='linear')
svClassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [36]:
# Kernel svm
from sklearn.svm import SVC
ksvClassifier = SVC(kernel='rbf')
ksvClassifier.fit(X_train, y_train)

SVC()

In [37]:
# naives bayes classifier
from sklearn.naive_bayes import GaussianNB
nbClassifier = GaussianNB()
nbClassifier.fit(X_train, y_train)

GaussianNB()

In [38]:
# decision tree classifer
from sklearn.tree import DecisionTreeClassifier
dtClassifier = DecisionTreeClassifier(criterion='entropy')
dtClassifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [39]:
# Random forest classifier
from sklearn.ensemble import RandomForestClassifier
rfClassifier = RandomForestClassifier(n_estimators=100, criterion='entropy')
rfClassifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy')

In [54]:
y_pred_lr = lRegClassifier.predict(X_test)
y_pred_knn = knnClassifier.predict(X_test)
y_pred_SVC = svClassifier.predict(X_test)
y_pred_ksv = ksvClassifier.predict(X_test)
y_pred_nb = nbClassifier.predict(X_test)
y_pred_dt = dtClassifier.predict(X_test)
y_pred_rf = rfClassifier.predict(X_test)

In [56]:
# confsuion matrix
from sklearn.metrics import confusion_matrix, accuracy_score

cmlr = confusion_matrix(y_test, y_pred_lr)
print('{}\naccuarcy of Logistic Classifier is: {}\n'.format(cmlr, accuracy_score(y_test, y_pred_lr)))

cmknn = confusion_matrix(y_test, y_pred_knn)
print('{}\naccuarcy of KNN is: {}\n'.format(cmknn, accuracy_score(y_test, y_pred_knn)))

cmSCV = confusion_matrix(y_test, y_pred_SVC)
print('{}\naccuarcy of Support Vector Machine is: {}\n'.format(cmSCV, accuracy_score(y_test, y_pred_SVC)))

cmksv = confusion_matrix(y_test, y_pred_ksv)
print('{}\naccuarcy of Kernel SVM is: {}\n'.format(cmksv, accuracy_score(y_test, y_pred_ksv)))

cmnb = confusion_matrix(y_test, y_pred_nb)
print('{}\naccuarcy of Naive Bayes is: {}\n'.format(cmnb, accuracy_score(y_test, y_pred_nb)))

cmdt = confusion_matrix(y_test, y_pred_dt)
print('{}\naccuarcy of Decision tree is: {}\n'.format(cmdt, accuracy_score(y_test, y_pred_dt)))

cmrf = confusion_matrix(y_test, y_pred_rf)
print('{}\naccuarcy of Random forest is: {}\n'.format(cmrf, accuracy_score(y_test, y_pred_rf)))

[[84  3]
 [ 3 47]]
accuarcy of Logistic Classifier is: 0.9562043795620438

[[83  4]
 [ 2 48]]
accuarcy of KNN is: 0.9562043795620438

[[83  4]
 [ 2 48]]
accuarcy of Support Vector Machine is: 0.9562043795620438

[[82  5]
 [ 1 49]]
accuarcy of Kernel SVM is: 0.9562043795620438

[[80  7]
 [ 0 50]]
accuarcy of Naive Bayes is: 0.948905109489051

[[84  3]
 [ 3 47]]
accuarcy of Decision tree is: 0.9562043795620438

[[84  3]
 [ 1 49]]
accuarcy of Random forest is: 0.9708029197080292

